name: Build and Upload to S3

on:
  push:
    branches:
      - main  # or any branch you want to trigger the workflow

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build using Make
        run: |
          cd srcs/react
          make copy-build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload to S3
        run: |
          aws s3 cp public/build.js s3://www.ruslanbasyrov.com/build.js --acl public-read
